#
# complexity documentation build configuration file, created by
# sphinx-quickstart on Tue Jul  9 22:26:36 2013.
#
# This file is execfile()d with the current directory set to its containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import datetime
import os
import sys


# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
# sys.path.insert(0, os.path.abspath('.'))

cwd = os.getcwd()
parent = os.path.dirname(cwd)
sys.path.insert(0, parent)


# -- General configuration -----------------------------------------------------
extensions = [
    "sphinx.ext.viewcode",
    "sphinx.ext.intersphinx",
    "sphinx.ext.extlinks",
    "myst_nb",
    "sphinx_codeautolink",
    "sphinx_copybutton",
    "sphinx_remove_toctrees",
    "sphinxext.opengraph",
    "sphinx_design",
]

autodoc_typehints = "none"
codeautolink_concat_default = True

extlinks = {
    "issue": ("https://github.com/pydata/xarray/issues/%s", "GH#%s"),
    "pr": ("https://github.com/pydata/xarray/pull/%s", "PR#%s"),
}

templates_path = ["_templates"]
source_suffix = {
    ".rst": "restructuredtext",
    ".md": "myst-nb",
    ".ipynb": "myst-nb",
}
master_doc = "index"
language = "en"

remove_from_toctrees = ["generated/*"]

# General information about the project.
project = "sphinx_book_theme"
current_year = datetime.datetime.now().year
copyright = f"2025-{current_year}, Xarray contributors"
author = "Xarray Contributors"

# Myst_nb options
nb_execution_excludepatterns = []
nb_execution_raise_on_error = True
nb_execution_mode = "cache"
nb_execution_show_tb = True
nb_remove_cell_tags = ["remove-cell"]

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ["_build"]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "igor"

ogp_site_url = "https://xarray_gallery.readthedocs.io/"


# -- Options for HTML output ---------------------------------------------------

html_theme = "sphinx_book_theme"
# html_logo = "Xarray.png"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
css_vars = {
    "admonition-font-size": "0.9rem",
    "font-size--small": "92%",
    "font-size--small--2": "87.5%",
}

html_context = {
    "github_user": "xarray-contrib",
    "github_repo": "xarray-indexes",
    "github_version": "main",
    "doc_path": "doc",
}
html_title = "Xarray Indexes Gallery"
html_static_path = ["_static"]
html_css_files = ["style.css"]
htmlhelp_basename = "Xarraydoc"

intersphinx_mapping = {
    "python": ("https://docs.python.org/3/", None),
    "pandas": ("https://pandas.pydata.org/pandas-docs/stable", None),
    "numpy": ("https://numpy.org/doc/stable", None),
    "xarray": ("https://docs.xarray.dev/en/stable/", None),
    "rasterix": ("https://rasterix.readthedocs.io/en/latest/", None),
    "shapely": ("https://shapely.readthedocs.io/en/latest/", None),
    "xvec": ("https://xvec.readthedocs.io/en/stable/", None),
    "geopandas": ("https://geopandas.readthedocs.io/en/stable/", None),
}
